name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      ref:
        description: 'Git ref (tag or branch) to release from'
        required: false
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: node:24-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        run: |-
          tar -czf release-dark.tar.gz -C dist-dark .
          tar -czf release-light.tar.gz -C dist-light .
          mv dist-light/ dist-dark/
          mv dist-dark/dist-light/ dist-dark/light/
          tar -czf release-cmobined.tar.gz -C dist-dark .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.ref || github.ref_name }}
          files: |
            release-dark.tar.gz
            release-light.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
