name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      ref:
        description: 'Git ref (tag or branch) to release from'
        required: false
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: node:22-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        run: |-
          tar -czf release.tar.gz -C dist .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.ref || github.ref_name }}
          files: release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
